/**
 * 全量 Emoji 词汇库 - 幼儿英语学习
 * 包含各类名词、动词的 emoji 词汇
 */

const WordsData = {
  // ==================== 水果 Fruits ====================
  fruits: [
    { name: 'Apple', chinese: '苹果', emoji: '🍎' },
    { name: 'Green Apple', chinese: '青苹果', emoji: '🍏' },
    { name: 'Pear', chinese: '梨', emoji: '🍐' },
    { name: 'Orange', chinese: '橙子', emoji: '🍊' },
    { name: 'Lemon', chinese: '柠檬', emoji: '🍋' },
    { name: 'Banana', chinese: '香蕉', emoji: '🍌' },
    { name: 'Watermelon', chinese: '西瓜', emoji: '🍉' },
    { name: 'Grapes', chinese: '葡萄', emoji: '🍇' },
    { name: 'Strawberry', chinese: '草莓', emoji: '🍓' },
    { name: 'Blueberries', chinese: '蓝莓', emoji: '🫐' },
    { name: 'Melon', chinese: '甜瓜', emoji: '🍈' },
    { name: 'Cherry', chinese: '樱桃', emoji: '🍒' },
    { name: 'Peach', chinese: '桃子', emoji: '🍑' },
    { name: 'Mango', chinese: '芒果', emoji: '🥭' },
    { name: 'Pineapple', chinese: '菠萝', emoji: '🍍' },
    { name: 'Coconut', chinese: '椰子', emoji: '🥥' },
    { name: 'Kiwi', chinese: '猕猴桃', emoji: '🥝' },
    { name: 'Tomato', chinese: '番茄', emoji: '🍅' },
    { name: 'Avocado', chinese: '牛油果', emoji: '🥑' },
  ],

  // ==================== 蔬菜 Vegetables ====================
  vegetables: [
    { name: 'Carrot', chinese: '胡萝卜', emoji: '🥕' },
    { name: 'Corn', chinese: '玉米', emoji: '🌽' },
    { name: 'Hot Pepper', chinese: '辣椒', emoji: '🌶️' },
    { name: 'Bell Pepper', chinese: '甜椒', emoji: '🫑' },
    { name: 'Cucumber', chinese: '黄瓜', emoji: '🥒' },
    { name: 'Lettuce', chinese: '生菜', emoji: '🥬' },
    { name: 'Broccoli', chinese: '西兰花', emoji: '🥦' },
    { name: 'Garlic', chinese: '大蒜', emoji: '🧄' },
    { name: 'Onion', chinese: '洋葱', emoji: '🧅' },
    { name: 'Mushroom', chinese: '蘑菇', emoji: '🍄' },
    { name: 'Potato', chinese: '土豆', emoji: '🥔' },
    { name: 'Sweet Potato', chinese: '红薯', emoji: '🍠' },
    { name: 'Eggplant', chinese: '茄子', emoji: '🍆' },
    { name: 'Peanuts', chinese: '花生', emoji: '🥜' },
    { name: 'Chestnut', chinese: '栗子', emoji: '🌰' },
    { name: 'Beans', chinese: '豆子', emoji: '🫘' },
    { name: 'Ginger', chinese: '生姜', emoji: '🫚' },
  ],

  // ==================== 食物 Food ====================
  food: [
    { name: 'Bread', chinese: '面包', emoji: '🍞' },
    { name: 'Croissant', chinese: '牛角包', emoji: '🥐' },
    { name: 'Baguette', chinese: '法棍', emoji: '🥖' },
    { name: 'Pretzel', chinese: '椒盐卷饼', emoji: '🥨' },
    { name: 'Bagel', chinese: '百吉饼', emoji: '🥯' },
    { name: 'Pancakes', chinese: '煎饼', emoji: '🥞' },
    { name: 'Waffle', chinese: '华夫饼', emoji: '🧇' },
    { name: 'Cheese', chinese: '奶酪', emoji: '🧀' },
    { name: 'Egg', chinese: '鸡蛋', emoji: '🥚' },
    { name: 'Fried Egg', chinese: '煎蛋', emoji: '🍳' },
    { name: 'Bacon', chinese: '培根', emoji: '🥓' },
    { name: 'Meat', chinese: '肉', emoji: '🥩' },
    { name: 'Chicken', chinese: '鸡腿', emoji: '🍗' },
    { name: 'Hot Dog', chinese: '热狗', emoji: '🌭' },
    { name: 'Hamburger', chinese: '汉堡', emoji: '🍔' },
    { name: 'French Fries', chinese: '薯条', emoji: '🍟' },
    { name: 'Pizza', chinese: '披萨', emoji: '🍕' },
    { name: 'Sandwich', chinese: '三明治', emoji: '🥪' },
    { name: 'Taco', chinese: '墨西哥卷', emoji: '🌮' },
    { name: 'Burrito', chinese: '卷饼', emoji: '🌯' },
    { name: 'Salad', chinese: '沙拉', emoji: '🥗' },
    { name: 'Soup', chinese: '汤', emoji: '🍲' },
    { name: 'Noodles', chinese: '面条', emoji: '🍜' },
    { name: 'Spaghetti', chinese: '意大利面', emoji: '🍝' },
    { name: 'Rice', chinese: '米饭', emoji: '🍚' },
    { name: 'Curry', chinese: '咖喱', emoji: '🍛' },
    { name: 'Sushi', chinese: '寿司', emoji: '🍣' },
    { name: 'Dumpling', chinese: '饺子', emoji: '🥟' },
    { name: 'Cookie', chinese: '饼干', emoji: '🍪' },
    { name: 'Cake', chinese: '蛋糕', emoji: '🍰' },
    { name: 'Birthday Cake', chinese: '生日蛋糕', emoji: '🎂' },
    { name: 'Pie', chinese: '派', emoji: '🥧' },
    { name: 'Chocolate', chinese: '巧克力', emoji: '🍫' },
    { name: 'Candy', chinese: '糖果', emoji: '🍬' },
    { name: 'Lollipop', chinese: '棒棒糖', emoji: '🍭' },
    { name: 'Doughnut', chinese: '甜甜圈', emoji: '🍩' },
    { name: 'Cupcake', chinese: '纸杯蛋糕', emoji: '🧁' },
    { name: 'Ice Cream', chinese: '冰淇淋', emoji: '🍦' },
    { name: 'Honey', chinese: '蜂蜜', emoji: '🍯' },
    { name: 'Popcorn', chinese: '爆米花', emoji: '🍿' },
    { name: 'Salt', chinese: '盐', emoji: '🧂' },
    { name: 'Butter', chinese: '黄油', emoji: '🧈' },
  ],

  // ==================== 饮料 Drinks ====================
  drinks: [
    { name: 'Water', chinese: '水', emoji: '💧' },
    { name: 'Milk', chinese: '牛奶', emoji: '🥛' },
    { name: 'Baby Bottle', chinese: '奶瓶', emoji: '🍼' },
    { name: 'Coffee', chinese: '咖啡', emoji: '☕' },
    { name: 'Tea', chinese: '茶', emoji: '🍵' },
    { name: 'Juice', chinese: '果汁', emoji: '🧃' },
    { name: 'Soda', chinese: '汽水', emoji: '🥤' },
    { name: 'Beer', chinese: '啤酒', emoji: '🍺' },
    { name: 'Wine', chinese: '葡萄酒', emoji: '🍷' },
    { name: 'Cocktail', chinese: '鸡尾酒', emoji: '🍸' },
    { name: 'Ice', chinese: '冰块', emoji: '🧊' },
    { name: 'Bubble Tea', chinese: '奶茶', emoji: '🧋' },
  ],

  // ==================== 动物 Animals ====================
  animals: [
    // 哺乳动物
    { name: 'Dog', chinese: '狗', emoji: '🐶' },
    { name: 'Cat', chinese: '猫', emoji: '🐱' },
    { name: 'Mouse', chinese: '老鼠', emoji: '🐭' },
    { name: 'Hamster', chinese: '仓鼠', emoji: '🐹' },
    { name: 'Rabbit', chinese: '兔子', emoji: '🐰' },
    { name: 'Fox', chinese: '狐狸', emoji: '🦊' },
    { name: 'Bear', chinese: '熊', emoji: '🐻' },
    { name: 'Panda', chinese: '熊猫', emoji: '🐼' },
    { name: 'Koala', chinese: '考拉', emoji: '🐨' },
    { name: 'Tiger', chinese: '老虎', emoji: '🐯' },
    { name: 'Lion', chinese: '狮子', emoji: '🦁' },
    { name: 'Cow', chinese: '牛', emoji: '🐮' },
    { name: 'Pig', chinese: '猪', emoji: '🐷' },
    { name: 'Frog', chinese: '青蛙', emoji: '🐸' },
    { name: 'Monkey', chinese: '猴子', emoji: '🐵' },
    { name: 'Gorilla', chinese: '大猩猩', emoji: '🦍' },
    { name: 'Elephant', chinese: '大象', emoji: '🐘' },
    { name: 'Horse', chinese: '马', emoji: '🐴' },
    { name: 'Unicorn', chinese: '独角兽', emoji: '🦄' },
    { name: 'Zebra', chinese: '斑马', emoji: '🦓' },
    { name: 'Deer', chinese: '鹿', emoji: '🦌' },
    { name: 'Giraffe', chinese: '长颈鹿', emoji: '🦒' },
    { name: 'Camel', chinese: '骆驼', emoji: '🐫' },
    { name: 'Llama', chinese: '羊驼', emoji: '🦙' },
    { name: 'Kangaroo', chinese: '袋鼠', emoji: '🦘' },
    { name: 'Sheep', chinese: '绵羊', emoji: '🐑' },
    { name: 'Goat', chinese: '山羊', emoji: '🐐' },
    { name: 'Wolf', chinese: '狼', emoji: '🐺' },
    { name: 'Raccoon', chinese: '浣熊', emoji: '🦝' },
    { name: 'Skunk', chinese: '臭鼬', emoji: '🦨' },
    { name: 'Badger', chinese: '獾', emoji: '🦡' },
    { name: 'Hedgehog', chinese: '刺猬', emoji: '🦔' },
    { name: 'Bat', chinese: '蝙蝠', emoji: '🦇' },
    { name: 'Otter', chinese: '水獭', emoji: '🦦' },
    { name: 'Sloth', chinese: '树懒', emoji: '🦥' },
    { name: 'Hippo', chinese: '河马', emoji: '🦛' },
    { name: 'Rhino', chinese: '犀牛', emoji: '🦏' },
    { name: 'Whale', chinese: '鲸鱼', emoji: '🐋' },
    { name: 'Dolphin', chinese: '海豚', emoji: '🐬' },
    { name: 'Seal', chinese: '海豹', emoji: '🦭' },
    // 鸟类
    { name: 'Bird', chinese: '小鸟', emoji: '🐦' },
    { name: 'Chicken', chinese: '小鸡', emoji: '🐔' },
    { name: 'Rooster', chinese: '公鸡', emoji: '🐓' },
    { name: 'Chick', chinese: '小黄鸡', emoji: '🐥' },
    { name: 'Duck', chinese: '鸭子', emoji: '🦆' },
    { name: 'Swan', chinese: '天鹅', emoji: '🦢' },
    { name: 'Goose', chinese: '鹅', emoji: '🪿' },
    { name: 'Owl', chinese: '猫头鹰', emoji: '🦉' },
    { name: 'Eagle', chinese: '鹰', emoji: '🦅' },
    { name: 'Peacock', chinese: '孔雀', emoji: '🦚' },
    { name: 'Parrot', chinese: '鹦鹉', emoji: '🦜' },
    { name: 'Flamingo', chinese: '火烈鸟', emoji: '🦩' },
    { name: 'Penguin', chinese: '企鹅', emoji: '🐧' },
    { name: 'Turkey', chinese: '火鸡', emoji: '🦃' },
    { name: 'Dove', chinese: '鸽子', emoji: '🕊️' },
    // 爬行动物和两栖动物
    { name: 'Crocodile', chinese: '鳄鱼', emoji: '🐊' },
    { name: 'Turtle', chinese: '乌龟', emoji: '🐢' },
    { name: 'Snake', chinese: '蛇', emoji: '🐍' },
    { name: 'Lizard', chinese: '蜥蜴', emoji: '🦎' },
    { name: 'Dragon', chinese: '龙', emoji: '🐉' },
    { name: 'Dinosaur', chinese: '恐龙', emoji: '🦕' },
    { name: 'T-Rex', chinese: '霸王龙', emoji: '🦖' },
    // 海洋生物
    { name: 'Fish', chinese: '鱼', emoji: '🐟' },
    { name: 'Tropical Fish', chinese: '热带鱼', emoji: '🐠' },
    { name: 'Blowfish', chinese: '河豚', emoji: '🐡' },
    { name: 'Shark', chinese: '鲨鱼', emoji: '🦈' },
    { name: 'Octopus', chinese: '章鱼', emoji: '🐙' },
    { name: 'Squid', chinese: '鱿鱼', emoji: '🦑' },
    { name: 'Shrimp', chinese: '虾', emoji: '🦐' },
    { name: 'Crab', chinese: '螃蟹', emoji: '🦀' },
    { name: 'Lobster', chinese: '龙虾', emoji: '🦞' },
    { name: 'Jellyfish', chinese: '水母', emoji: '🪼' },
    { name: 'Coral', chinese: '珊瑚', emoji: '🪸' },
    { name: 'Shell', chinese: '贝壳', emoji: '🐚' },
    // 昆虫
    { name: 'Snail', chinese: '蜗牛', emoji: '🐌' },
    { name: 'Butterfly', chinese: '蝴蝶', emoji: '🦋' },
    { name: 'Bug', chinese: '虫子', emoji: '🐛' },
    { name: 'Ant', chinese: '蚂蚁', emoji: '🐜' },
    { name: 'Bee', chinese: '蜜蜂', emoji: '🐝' },
    { name: 'Beetle', chinese: '甲虫', emoji: '🪲' },
    { name: 'Ladybug', chinese: '瓢虫', emoji: '🐞' },
    { name: 'Cricket', chinese: '蟋蟀', emoji: '🦗' },
    { name: 'Cockroach', chinese: '蟑螂', emoji: '🪳' },
    { name: 'Spider', chinese: '蜘蛛', emoji: '🕷️' },
    { name: 'Scorpion', chinese: '蝎子', emoji: '🦂' },
    { name: 'Mosquito', chinese: '蚊子', emoji: '🦟' },
    { name: 'Fly', chinese: '苍蝇', emoji: '🪰' },
    { name: 'Worm', chinese: '蠕虫', emoji: '🪱' },
    { name: 'Caterpillar', chinese: '毛毛虫', emoji: '🐛' },
  ],

  // ==================== 植物花卉 Plants ====================
  plants: [
    { name: 'Flower', chinese: '花', emoji: '🌸' },
    { name: 'Cherry Blossom', chinese: '樱花', emoji: '🌸' },
    { name: 'Rose', chinese: '玫瑰', emoji: '🌹' },
    { name: 'Tulip', chinese: '郁金香', emoji: '🌷' },
    { name: 'Sunflower', chinese: '向日葵', emoji: '🌻' },
    { name: 'Hibiscus', chinese: '木槿', emoji: '🌺' },
    { name: 'Lotus', chinese: '荷花', emoji: '🪷' },
    { name: 'Bouquet', chinese: '花束', emoji: '💐' },
    { name: 'Tree', chinese: '树', emoji: '🌳' },
    { name: 'Evergreen', chinese: '松树', emoji: '🌲' },
    { name: 'Palm Tree', chinese: '棕榈树', emoji: '🌴' },
    { name: 'Cactus', chinese: '仙人掌', emoji: '🌵' },
    { name: 'Plant', chinese: '盆栽', emoji: '🪴' },
    { name: 'Seedling', chinese: '幼苗', emoji: '🌱' },
    { name: 'Herb', chinese: '香草', emoji: '🌿' },
    { name: 'Shamrock', chinese: '三叶草', emoji: '☘️' },
    { name: 'Four Leaf Clover', chinese: '四叶草', emoji: '🍀' },
    { name: 'Maple Leaf', chinese: '枫叶', emoji: '🍁' },
    { name: 'Fallen Leaf', chinese: '落叶', emoji: '🍂' },
    { name: 'Leaves', chinese: '树叶', emoji: '🍃' },
    { name: 'Bamboo', chinese: '竹子', emoji: '🎋' },
    { name: 'Nest', chinese: '鸟巢', emoji: '🪹' },
    { name: 'Wood', chinese: '木头', emoji: '🪵' },
  ],

  // ==================== 天气自然 Weather & Nature ====================
  nature: [
    { name: 'Sun', chinese: '太阳', emoji: '☀️' },
    { name: 'Moon', chinese: '月亮', emoji: '🌙' },
    { name: 'Star', chinese: '星星', emoji: '⭐' },
    { name: 'Stars', chinese: '繁星', emoji: '🌟' },
    { name: 'Cloud', chinese: '云', emoji: '☁️' },
    { name: 'Rainbow', chinese: '彩虹', emoji: '🌈' },
    { name: 'Rain', chinese: '雨', emoji: '🌧️' },
    { name: 'Umbrella', chinese: '雨伞', emoji: '☂️' },
    { name: 'Snow', chinese: '雪', emoji: '❄️' },
    { name: 'Snowman', chinese: '雪人', emoji: '⛄' },
    { name: 'Snowflake', chinese: '雪花', emoji: '❄️' },
    { name: 'Thunder', chinese: '闪电', emoji: '⚡' },
    { name: 'Fire', chinese: '火', emoji: '🔥' },
    { name: 'Wind', chinese: '风', emoji: '💨' },
    { name: 'Tornado', chinese: '龙卷风', emoji: '🌪️' },
    { name: 'Fog', chinese: '雾', emoji: '🌫️' },
    { name: 'Wave', chinese: '海浪', emoji: '🌊' },
    { name: 'Droplet', chinese: '水滴', emoji: '💧' },
    { name: 'Earth', chinese: '地球', emoji: '🌍' },
    { name: 'Globe', chinese: '地球仪', emoji: '🌐' },
    { name: 'Map', chinese: '地图', emoji: '🗺️' },
    { name: 'Mountain', chinese: '山', emoji: '⛰️' },
    { name: 'Volcano', chinese: '火山', emoji: '🌋' },
    { name: 'Desert', chinese: '沙漠', emoji: '🏜️' },
    { name: 'Island', chinese: '岛屿', emoji: '🏝️' },
    { name: 'Beach', chinese: '海滩', emoji: '🏖️' },
    { name: 'Camping', chinese: '露营', emoji: '🏕️' },
    { name: 'Tent', chinese: '帐篷', emoji: '⛺' },
    { name: 'Rock', chinese: '岩石', emoji: '🪨' },
    { name: 'Comet', chinese: '彗星', emoji: '☄️' },
  ],

  // ==================== 运动 Sports ====================
  sports: [
    { name: 'Soccer', chinese: '足球', emoji: '⚽' },
    { name: 'Basketball', chinese: '篮球', emoji: '🏀' },
    { name: 'Football', chinese: '橄榄球', emoji: '🏈' },
    { name: 'Baseball', chinese: '棒球', emoji: '⚾' },
    { name: 'Tennis', chinese: '网球', emoji: '🎾' },
    { name: 'Volleyball', chinese: '排球', emoji: '🏐' },
    { name: 'Badminton', chinese: '羽毛球', emoji: '🏸' },
    { name: 'Ping Pong', chinese: '乒乓球', emoji: '🏓' },
    { name: 'Hockey', chinese: '冰球', emoji: '🏒' },
    { name: 'Golf', chinese: '高尔夫', emoji: '⛳' },
    { name: 'Bowling', chinese: '保龄球', emoji: '🎳' },
    { name: 'Fishing', chinese: '钓鱼', emoji: '🎣' },
    { name: 'Skiing', chinese: '滑雪', emoji: '⛷️' },
    { name: 'Snowboard', chinese: '滑雪板', emoji: '🏂' },
    { name: 'Skateboard', chinese: '滑板', emoji: '🛹' },
    { name: 'Surfing', chinese: '冲浪', emoji: '🏄' },
    { name: 'Swimming', chinese: '游泳', emoji: '🏊' },
    { name: 'Diving', chinese: '潜水', emoji: '🤿' },
    { name: 'Cycling', chinese: '骑车', emoji: '🚴' },
    { name: 'Running', chinese: '跑步', emoji: '🏃' },
    { name: 'Walking', chinese: '散步', emoji: '🚶' },
    { name: 'Boxing', chinese: '拳击', emoji: '🥊' },
    { name: 'Martial Arts', chinese: '武术', emoji: '🥋' },
    { name: 'Gymnastics', chinese: '体操', emoji: '🤸' },
    { name: 'Yoga', chinese: '瑜伽', emoji: '🧘' },
    { name: 'Horse Riding', chinese: '骑马', emoji: '🏇' },
    { name: 'Trophy', chinese: '奖杯', emoji: '🏆' },
    { name: 'Medal', chinese: '奖牌', emoji: '🏅' },
    { name: 'Target', chinese: '靶子', emoji: '🎯' },
    { name: 'Kite', chinese: '风筝', emoji: '🪁' },
  ],

  // ==================== 乐器音乐 Music ====================
  music: [
    { name: 'Music', chinese: '音乐', emoji: '🎵' },
    { name: 'Microphone', chinese: '麦克风', emoji: '🎤' },
    { name: 'Headphones', chinese: '耳机', emoji: '🎧' },
    { name: 'Radio', chinese: '收音机', emoji: '📻' },
    { name: 'Guitar', chinese: '吉他', emoji: '🎸' },
    { name: 'Piano', chinese: '钢琴', emoji: '🎹' },
    { name: 'Violin', chinese: '小提琴', emoji: '🎻' },
    { name: 'Trumpet', chinese: '小号', emoji: '🎺' },
    { name: 'Drum', chinese: '鼓', emoji: '🥁' },
    { name: 'Saxophone', chinese: '萨克斯', emoji: '🎷' },
    { name: 'Accordion', chinese: '手风琴', emoji: '🪗' },
    { name: 'Banjo', chinese: '班卓琴', emoji: '🪕' },
    { name: 'Maracas', chinese: '沙锤', emoji: '🪇' },
    { name: 'Flute', chinese: '长笛', emoji: '🪈' },
    { name: 'Bell', chinese: '铃铛', emoji: '🔔' },
  ],

  // ==================== 衣服配饰 Clothing ====================
  clothing: [
    { name: 'T-Shirt', chinese: 'T恤', emoji: '👕' },
    { name: 'Jeans', chinese: '牛仔裤', emoji: '👖' },
    { name: 'Dress', chinese: '连衣裙', emoji: '👗' },
    { name: 'Kimono', chinese: '和服', emoji: '👘' },
    { name: 'Bikini', chinese: '比基尼', emoji: '👙' },
    { name: 'Coat', chinese: '外套', emoji: '🧥' },
    { name: 'Sweater', chinese: '毛衣', emoji: '🧶' },
    { name: 'Scarf', chinese: '围巾', emoji: '🧣' },
    { name: 'Gloves', chinese: '手套', emoji: '🧤' },
    { name: 'Socks', chinese: '袜子', emoji: '🧦' },
    { name: 'Shoe', chinese: '鞋子', emoji: '👟' },
    { name: 'High Heel', chinese: '高跟鞋', emoji: '👠' },
    { name: 'Sandal', chinese: '凉鞋', emoji: '👡' },
    { name: 'Boot', chinese: '靴子', emoji: '👢' },
    { name: 'Flip Flops', chinese: '拖鞋', emoji: '🩴' },
    { name: 'Hat', chinese: '帽子', emoji: '🎩' },
    { name: 'Cap', chinese: '鸭舌帽', emoji: '🧢' },
    { name: 'Crown', chinese: '皇冠', emoji: '👑' },
    { name: 'Glasses', chinese: '眼镜', emoji: '👓' },
    { name: 'Sunglasses', chinese: '太阳镜', emoji: '🕶️' },
    { name: 'Tie', chinese: '领带', emoji: '👔' },
    { name: 'Backpack', chinese: '书包', emoji: '🎒' },
    { name: 'Handbag', chinese: '手提包', emoji: '👜' },
    { name: 'Purse', chinese: '钱包', emoji: '👛' },
    { name: 'Briefcase', chinese: '公文包', emoji: '💼' },
    { name: 'Umbrella', chinese: '雨伞', emoji: '☂️' },
    { name: 'Ring', chinese: '戒指', emoji: '💍' },
    { name: 'Lipstick', chinese: '口红', emoji: '💄' },
    { name: 'Gem', chinese: '宝石', emoji: '💎' },
  ],

  // ==================== 建筑地点 Buildings ====================
  buildings: [
    { name: 'House', chinese: '房子', emoji: '🏠' },
    { name: 'Home', chinese: '家', emoji: '🏡' },
    { name: 'Building', chinese: '大楼', emoji: '🏢' },
    { name: 'Office', chinese: '办公楼', emoji: '🏢' },
    { name: 'Hospital', chinese: '医院', emoji: '🏥' },
    { name: 'Bank', chinese: '银行', emoji: '🏦' },
    { name: 'Hotel', chinese: '酒店', emoji: '🏨' },
    { name: 'School', chinese: '学校', emoji: '🏫' },
    { name: 'Store', chinese: '商店', emoji: '🏪' },
    { name: 'Factory', chinese: '工厂', emoji: '🏭' },
    { name: 'Castle', chinese: '城堡', emoji: '🏰' },
    { name: 'Church', chinese: '教堂', emoji: '⛪' },
    { name: 'Mosque', chinese: '清真寺', emoji: '🕌' },
    { name: 'Temple', chinese: '寺庙', emoji: '🛕' },
    { name: 'Stadium', chinese: '体育场', emoji: '🏟️' },
    { name: 'Tent', chinese: '帐篷', emoji: '⛺' },
    { name: 'Hut', chinese: '小屋', emoji: '🛖' },
    { name: 'Tower', chinese: '塔', emoji: '🗼' },
    { name: 'Statue', chinese: '雕像', emoji: '🗽' },
    { name: 'Fountain', chinese: '喷泉', emoji: '⛲' },
    { name: 'Ferris Wheel', chinese: '摩天轮', emoji: '🎡' },
    { name: 'Roller Coaster', chinese: '过山车', emoji: '🎢' },
    { name: 'Carousel', chinese: '旋转木马', emoji: '🎠' },
    { name: 'Playground', chinese: '游乐场', emoji: '🛝' },
    { name: 'Bridge', chinese: '桥', emoji: '🌉' },
  ],

  // ==================== 工具物品 Tools & Objects ====================
  tools: [
    { name: 'Hammer', chinese: '锤子', emoji: '🔨' },
    { name: 'Axe', chinese: '斧头', emoji: '🪓' },
    { name: 'Saw', chinese: '锯子', emoji: '🪚' },
    { name: 'Screwdriver', chinese: '螺丝刀', emoji: '🪛' },
    { name: 'Wrench', chinese: '扳手', emoji: '🔧' },
    { name: 'Plunger', chinese: '搋子', emoji: '🪠' },
    { name: 'Toolbox', chinese: '工具箱', emoji: '🧰' },
    { name: 'Magnet', chinese: '磁铁', emoji: '🧲' },
    { name: 'Ladder', chinese: '梯子', emoji: '🪜' },
    { name: 'Scissors', chinese: '剪刀', emoji: '✂️' },
    { name: 'Knife', chinese: '刀', emoji: '🔪' },
    { name: 'Broom', chinese: '扫帚', emoji: '🧹' },
    { name: 'Bucket', chinese: '水桶', emoji: '🪣' },
    { name: 'Basket', chinese: '篮子', emoji: '🧺' },
    { name: 'Key', chinese: '钥匙', emoji: '🔑' },
    { name: 'Lock', chinese: '锁', emoji: '🔒' },
    { name: 'Flashlight', chinese: '手电筒', emoji: '🔦' },
    { name: 'Candle', chinese: '蜡烛', emoji: '🕯️' },
    { name: 'Bulb', chinese: '灯泡', emoji: '💡' },
    { name: 'Battery', chinese: '电池', emoji: '🔋' },
    { name: 'Plug', chinese: '插头', emoji: '🔌' },
    { name: 'Magnifier', chinese: '放大镜', emoji: '🔍' },
    { name: 'Microscope', chinese: '显微镜', emoji: '🔬' },
    { name: 'Telescope', chinese: '望远镜', emoji: '🔭' },
    { name: 'Compass', chinese: '指南针', emoji: '🧭' },
    { name: 'Hourglass', chinese: '沙漏', emoji: '⏳' },
    { name: 'Alarm Clock', chinese: '闹钟', emoji: '⏰' },
    { name: 'Watch', chinese: '手表', emoji: '⌚' },
    { name: 'Thermometer', chinese: '温度计', emoji: '🌡️' },
    { name: 'Scale', chinese: '秤', emoji: '⚖️' },
  ],

  // ==================== 电子设备 Electronics ====================
  electronics: [
    { name: 'Phone', chinese: '手机', emoji: '📱' },
    { name: 'Telephone', chinese: '电话', emoji: '📞' },
    { name: 'Computer', chinese: '电脑', emoji: '💻' },
    { name: 'Desktop', chinese: '台式电脑', emoji: '🖥️' },
    { name: 'Keyboard', chinese: '键盘', emoji: '⌨️' },
    { name: 'Mouse', chinese: '鼠标', emoji: '🖱️' },
    { name: 'Printer', chinese: '打印机', emoji: '🖨️' },
    { name: 'Tablet', chinese: '平板', emoji: '📱' },
    { name: 'Camera', chinese: '相机', emoji: '📷' },
    { name: 'Video Camera', chinese: '摄像机', emoji: '📹' },
    { name: 'Television', chinese: '电视', emoji: '📺' },
    { name: 'Remote', chinese: '遥控器', emoji: '📟' },
    { name: 'Game Controller', chinese: '游戏手柄', emoji: '🎮' },
    { name: 'Joystick', chinese: '摇杆', emoji: '🕹️' },
    { name: 'Robot', chinese: '机器人', emoji: '🤖' },
    { name: 'Satellite', chinese: '卫星', emoji: '🛰️' },
    { name: 'Rocket', chinese: '火箭', emoji: '🚀' },
    { name: 'UFO', chinese: '飞碟', emoji: '🛸' },
  ],

  // ==================== 学习办公 School & Office ====================
  school: [
    { name: 'Book', chinese: '书', emoji: '📕' },
    { name: 'Books', chinese: '书籍', emoji: '📚' },
    { name: 'Notebook', chinese: '笔记本', emoji: '📓' },
    { name: 'Pencil', chinese: '铅笔', emoji: '✏️' },
    { name: 'Pen', chinese: '钢笔', emoji: '🖊️' },
    { name: 'Crayon', chinese: '蜡笔', emoji: '🖍️' },
    { name: 'Marker', chinese: '马克笔', emoji: '🖌️' },
    { name: 'Ruler', chinese: '尺子', emoji: '📏' },
    { name: 'Paperclip', chinese: '回形针', emoji: '📎' },
    { name: 'Scissors', chinese: '剪刀', emoji: '✂️' },
    { name: 'Glue', chinese: '胶水', emoji: '🧴' },
    { name: 'Tape', chinese: '胶带', emoji: '📋' },
    { name: 'Calendar', chinese: '日历', emoji: '📅' },
    { name: 'Clipboard', chinese: '剪贴板', emoji: '📋' },
    { name: 'Folder', chinese: '文件夹', emoji: '📁' },
    { name: 'Envelope', chinese: '信封', emoji: '✉️' },
    { name: 'Letter', chinese: '信', emoji: '💌' },
    { name: 'Newspaper', chinese: '报纸', emoji: '📰' },
    { name: 'Diploma', chinese: '毕业证', emoji: '📜' },
    { name: 'Graduation Cap', chinese: '学士帽', emoji: '🎓' },
    { name: 'Blackboard', chinese: '黑板', emoji: '🖼️' },
    { name: 'Abacus', chinese: '算盘', emoji: '🧮' },
    { name: 'Globe', chinese: '地球仪', emoji: '🌐' },
  ],

  // ==================== 家具家居 Furniture ====================
  furniture: [
    { name: 'Door', chinese: '门', emoji: '🚪' },
    { name: 'Window', chinese: '窗户', emoji: '🪟' },
    { name: 'Bed', chinese: '床', emoji: '🛏️' },
    { name: 'Couch', chinese: '沙发', emoji: '🛋️' },
    { name: 'Chair', chinese: '椅子', emoji: '🪑' },
    { name: 'Toilet', chinese: '马桶', emoji: '🚽' },
    { name: 'Shower', chinese: '淋浴', emoji: '🚿' },
    { name: 'Bathtub', chinese: '浴缸', emoji: '🛁' },
    { name: 'Mirror', chinese: '镜子', emoji: '🪞' },
    { name: 'Lamp', chinese: '台灯', emoji: '🪔' },
    { name: 'Picture Frame', chinese: '相框', emoji: '🖼️' },
    { name: 'Vase', chinese: '花瓶', emoji: '🏺' },
    { name: 'Trash Can', chinese: '垃圾桶', emoji: '🗑️' },
  ],

  // ==================== 厨房用品 Kitchen ====================
  kitchen: [
    { name: 'Fork', chinese: '叉子', emoji: '🍴' },
    { name: 'Spoon', chinese: '勺子', emoji: '🥄' },
    { name: 'Knife', chinese: '刀', emoji: '🔪' },
    { name: 'Chopsticks', chinese: '筷子', emoji: '🥢' },
    { name: 'Plate', chinese: '盘子', emoji: '🍽️' },
    { name: 'Bowl', chinese: '碗', emoji: '🥣' },
    { name: 'Cup', chinese: '杯子', emoji: '🥤' },
    { name: 'Glass', chinese: '玻璃杯', emoji: '🥃' },
    { name: 'Mug', chinese: '马克杯', emoji: '☕' },
    { name: 'Teapot', chinese: '茶壶', emoji: '🫖' },
    { name: 'Bottle', chinese: '瓶子', emoji: '🍾' },
    { name: 'Jar', chinese: '罐子', emoji: '🫙' },
    { name: 'Pot', chinese: '锅', emoji: '🍲' },
    { name: 'Pan', chinese: '平底锅', emoji: '🍳' },
  ],

  // ==================== 玩具游戏 Toys & Games ====================
  toys: [
    { name: 'Teddy Bear', chinese: '泰迪熊', emoji: '🧸' },
    { name: 'Doll', chinese: '娃娃', emoji: '🪆' },
    { name: 'Yo-Yo', chinese: '悠悠球', emoji: '🪀' },
    { name: 'Kite', chinese: '风筝', emoji: '🪁' },
    { name: 'Puzzle', chinese: '拼图', emoji: '🧩' },
    { name: 'Dice', chinese: '骰子', emoji: '🎲' },
    { name: 'Chess', chinese: '国际象棋', emoji: '♟️' },
    { name: 'Playing Cards', chinese: '扑克牌', emoji: '🃏' },
    { name: 'Balloon', chinese: '气球', emoji: '🎈' },
    { name: 'Party', chinese: '派对', emoji: '🎉' },
    { name: 'Gift', chinese: '礼物', emoji: '🎁' },
    { name: 'Ribbon', chinese: '丝带', emoji: '🎀' },
    { name: 'Pinata', chinese: '皮纳塔', emoji: '🪅' },
    { name: 'Mirror Ball', chinese: '迪斯科球', emoji: '🪩' },
    { name: 'Fireworks', chinese: '烟花', emoji: '🎆' },
    { name: 'Sparkler', chinese: '烟火棒', emoji: '🎇' },
    { name: 'Magic Wand', chinese: '魔法棒', emoji: '🪄' },
    { name: 'Crystal Ball', chinese: '水晶球', emoji: '🔮' },
  ],

  // ==================== 身体部位 Body Parts ====================
  body: [
    { name: 'Eye', chinese: '眼睛', emoji: '👁️' },
    { name: 'Ear', chinese: '耳朵', emoji: '👂' },
    { name: 'Nose', chinese: '鼻子', emoji: '👃' },
    { name: 'Mouth', chinese: '嘴巴', emoji: '👄' },
    { name: 'Tongue', chinese: '舌头', emoji: '👅' },
    { name: 'Tooth', chinese: '牙齿', emoji: '🦷' },
    { name: 'Bone', chinese: '骨头', emoji: '🦴' },
    { name: 'Brain', chinese: '大脑', emoji: '🧠' },
    { name: 'Heart', chinese: '心脏', emoji: '❤️' },
    { name: 'Lungs', chinese: '肺', emoji: '🫁' },
    { name: 'Hand', chinese: '手', emoji: '✋' },
    { name: 'Foot', chinese: '脚', emoji: '🦶' },
    { name: 'Leg', chinese: '腿', emoji: '🦵' },
    { name: 'Muscle', chinese: '肌肉', emoji: '💪' },
    { name: 'Baby', chinese: '宝宝', emoji: '👶' },
    { name: 'Boy', chinese: '男孩', emoji: '👦' },
    { name: 'Girl', chinese: '女孩', emoji: '👧' },
    { name: 'Man', chinese: '男人', emoji: '👨' },
    { name: 'Woman', chinese: '女人', emoji: '👩' },
    { name: 'Family', chinese: '家庭', emoji: '👨‍👩‍👧' },
  ],

  // ==================== 职业 Jobs ====================
  jobs: [
    { name: 'Doctor', chinese: '医生', emoji: '👨‍⚕️' },
    { name: 'Nurse', chinese: '护士', emoji: '👩‍⚕️' },
    { name: 'Teacher', chinese: '老师', emoji: '👨‍🏫' },
    { name: 'Student', chinese: '学生', emoji: '👨‍🎓' },
    { name: 'Chef', chinese: '厨师', emoji: '👨‍🍳' },
    { name: 'Farmer', chinese: '农民', emoji: '👨‍🌾' },
    { name: 'Scientist', chinese: '科学家', emoji: '👨‍🔬' },
    { name: 'Artist', chinese: '艺术家', emoji: '👨‍🎨' },
    { name: 'Singer', chinese: '歌手', emoji: '👨‍🎤' },
    { name: 'Pilot', chinese: '飞行员', emoji: '👨‍✈️' },
    { name: 'Astronaut', chinese: '宇航员', emoji: '👨‍🚀' },
    { name: 'Firefighter', chinese: '消防员', emoji: '👨‍🚒' },
    { name: 'Police', chinese: '警察', emoji: '👮' },
    { name: 'Detective', chinese: '侦探', emoji: '🕵️' },
    { name: 'Guard', chinese: '保安', emoji: '💂' },
    { name: 'Worker', chinese: '工人', emoji: '👷' },
    { name: 'Mechanic', chinese: '机械师', emoji: '👨‍🔧' },
    { name: 'Judge', chinese: '法官', emoji: '👨‍⚖️' },
    { name: 'King', chinese: '国王', emoji: '🤴' },
    { name: 'Queen', chinese: '女王', emoji: '👸' },
    { name: 'Princess', chinese: '公主', emoji: '👸' },
    { name: 'Prince', chinese: '王子', emoji: '🤴' },
    { name: 'Santa', chinese: '圣诞老人', emoji: '🎅' },
    { name: 'Fairy', chinese: '仙女', emoji: '🧚' },
    { name: 'Mermaid', chinese: '美人鱼', emoji: '🧜' },
    { name: 'Superhero', chinese: '超级英雄', emoji: '🦸' },
    { name: 'Ninja', chinese: '忍者', emoji: '🥷' },
  ],

  // ==================== 表情动作 Expressions ====================
  expressions: [
    { name: 'Smile', chinese: '微笑', emoji: '😊' },
    { name: 'Laugh', chinese: '大笑', emoji: '😂' },
    { name: 'Cry', chinese: '哭泣', emoji: '😢' },
    { name: 'Angry', chinese: '生气', emoji: '😠' },
    { name: 'Scared', chinese: '害怕', emoji: '😨' },
    { name: 'Surprised', chinese: '惊讶', emoji: '😮' },
    { name: 'Sleepy', chinese: '困倦', emoji: '😴' },
    { name: 'Sick', chinese: '生病', emoji: '🤒' },
    { name: 'Love', chinese: '爱', emoji: '😍' },
    { name: 'Think', chinese: '思考', emoji: '🤔' },
    { name: 'Kiss', chinese: '亲吻', emoji: '😘' },
    { name: 'Wink', chinese: '眨眼', emoji: '😉' },
    { name: 'Cool', chinese: '酷', emoji: '😎' },
    { name: 'Clap', chinese: '鼓掌', emoji: '👏' },
    { name: 'Wave', chinese: '挥手', emoji: '👋' },
    { name: 'Point', chinese: '指向', emoji: '👉' },
    { name: 'Thumbs Up', chinese: '点赞', emoji: '👍' },
    { name: 'Pray', chinese: '祈祷', emoji: '🙏' },
    { name: 'Hug', chinese: '拥抱', emoji: '🤗' },
  ],

  // ==================== 交通工具（简化版，完整版在vehicles-data.js）====================
  vehicles: [
    { name: 'Car', chinese: '汽车', emoji: '🚗' },
    { name: 'Bus', chinese: '公交车', emoji: '🚌' },
    { name: 'Truck', chinese: '卡车', emoji: '🚚' },
    { name: 'Train', chinese: '火车', emoji: '🚂' },
    { name: 'Airplane', chinese: '飞机', emoji: '✈️' },
    { name: 'Helicopter', chinese: '直升机', emoji: '🚁' },
    { name: 'Boat', chinese: '船', emoji: '⛵' },
    { name: 'Rocket', chinese: '火箭', emoji: '🚀' },
    { name: 'Bicycle', chinese: '自行车', emoji: '🚲' },
    { name: 'Motorcycle', chinese: '摩托车', emoji: '🏍️' },
  ],

  // ==================== 数字 Numbers ====================
  numbers: [
    { name: 'One', chinese: '一', emoji: '1️⃣' },
    { name: 'Two', chinese: '二', emoji: '2️⃣' },
    { name: 'Three', chinese: '三', emoji: '3️⃣' },
    { name: 'Four', chinese: '四', emoji: '4️⃣' },
    { name: 'Five', chinese: '五', emoji: '5️⃣' },
    { name: 'Six', chinese: '六', emoji: '6️⃣' },
    { name: 'Seven', chinese: '七', emoji: '7️⃣' },
    { name: 'Eight', chinese: '八', emoji: '8️⃣' },
    { name: 'Nine', chinese: '九', emoji: '9️⃣' },
    { name: 'Ten', chinese: '十', emoji: '🔟' },
    { name: 'Hundred', chinese: '一百', emoji: '💯' },
  ],

  // ==================== 颜色 Colors ====================
  colors: [
    { name: 'Red', chinese: '红色', emoji: '❤️', hex: '#e74c3c' },
    { name: 'Orange', chinese: '橙色', emoji: '🧡', hex: '#e67e22' },
    { name: 'Yellow', chinese: '黄色', emoji: '💛', hex: '#f1c40f' },
    { name: 'Green', chinese: '绿色', emoji: '💚', hex: '#27ae60' },
    { name: 'Blue', chinese: '蓝色', emoji: '💙', hex: '#3498db' },
    { name: 'Purple', chinese: '紫色', emoji: '💜', hex: '#9b59b6' },
    { name: 'Pink', chinese: '粉色', emoji: '💗', hex: '#ff69b4' },
    { name: 'Brown', chinese: '棕色', emoji: '🤎', hex: '#8b4513' },
    { name: 'White', chinese: '白色', emoji: '🤍', hex: '#ffffff' },
    { name: 'Black', chinese: '黑色', emoji: '🖤', hex: '#2c3e50' },
  ],

  // ==================== 字母 Letters ====================
  letters: [
    { name: 'Apple', chinese: '苹果', emoji: '🍎', letter: 'A' },
    { name: 'Ball', chinese: '球', emoji: '⚽', letter: 'B' },
    { name: 'Cat', chinese: '猫', emoji: '🐱', letter: 'C' },
    { name: 'Dog', chinese: '狗', emoji: '🐶', letter: 'D' },
    { name: 'Elephant', chinese: '大象', emoji: '🐘', letter: 'E' },
    { name: 'Fish', chinese: '鱼', emoji: '🐟', letter: 'F' },
    { name: 'Gift', chinese: '礼物', emoji: '🎁', letter: 'G' },
    { name: 'House', chinese: '房子', emoji: '🏠', letter: 'H' },
    { name: 'Ice Cream', chinese: '冰淇淋', emoji: '🍦', letter: 'I' },
    { name: 'Jet', chinese: '喷气机', emoji: '✈️', letter: 'J' },
    { name: 'Key', chinese: '钥匙', emoji: '🔑', letter: 'K' },
    { name: 'Lemon', chinese: '柠檬', emoji: '🍋', letter: 'L' },
    { name: 'Moon', chinese: '月亮', emoji: '🌙', letter: 'M' },
    { name: 'Note', chinese: '音符', emoji: '🎵', letter: 'N' },
    { name: 'Orange', chinese: '橙子', emoji: '🍊', letter: 'O' },
    { name: 'Plane', chinese: '飞机', emoji: '✈️', letter: 'P' },
    { name: 'Queen', chinese: '女王', emoji: '👸', letter: 'Q' },
    { name: 'Rainbow', chinese: '彩虹', emoji: '🌈', letter: 'R' },
    { name: 'Star', chinese: '星星', emoji: '⭐', letter: 'S' },
    { name: 'Tree', chinese: '树', emoji: '🌳', letter: 'T' },
    { name: 'Umbrella', chinese: '雨伞', emoji: '☂️', letter: 'U' },
    { name: 'Van', chinese: '货车', emoji: '🚐', letter: 'V' },
    { name: 'Water', chinese: '水', emoji: '💧', letter: 'W' },
    { name: 'X-ray', chinese: 'X光', emoji: '🩻', letter: 'X' },
    { name: 'Yacht', chinese: '游艇', emoji: '⛵', letter: 'Y' },
    { name: 'Zebra', chinese: '斑马', emoji: '🦓', letter: 'Z' },
  ],

  /**
   * 获取所有分类
   */
  getCategories() {
    return [
      { key: 'letters', name: 'Letters', chinese: '字母', emoji: '🔤' },
      { key: 'numbers', name: 'Numbers', chinese: '数字', emoji: '🔢' },
      { key: 'colors', name: 'Colors', chinese: '颜色', emoji: '🎨' },
      { key: 'fruits', name: 'Fruits', chinese: '水果', emoji: '🍎' },
      { key: 'vegetables', name: 'Vegetables', chinese: '蔬菜', emoji: '🥕' },
      { key: 'food', name: 'Food', chinese: '食物', emoji: '🍔' },
      { key: 'drinks', name: 'Drinks', chinese: '饮料', emoji: '🥤' },
      { key: 'animals', name: 'Animals', chinese: '动物', emoji: '🐾' },
      { key: 'plants', name: 'Plants', chinese: '植物', emoji: '🌸' },
      { key: 'nature', name: 'Nature', chinese: '自然', emoji: '🌈' },
      { key: 'sports', name: 'Sports', chinese: '运动', emoji: '⚽' },
      { key: 'music', name: 'Music', chinese: '音乐', emoji: '🎵' },
      { key: 'clothing', name: 'Clothing', chinese: '衣服', emoji: '👕' },
      { key: 'buildings', name: 'Buildings', chinese: '建筑', emoji: '🏠' },
      { key: 'tools', name: 'Tools', chinese: '工具', emoji: '🔧' },
      { key: 'electronics', name: 'Electronics', chinese: '电子', emoji: '📱' },
      { key: 'school', name: 'School', chinese: '学习', emoji: '📚' },
      { key: 'furniture', name: 'Furniture', chinese: '家具', emoji: '🛋️' },
      { key: 'kitchen', name: 'Kitchen', chinese: '厨房', emoji: '🍴' },
      { key: 'toys', name: 'Toys', chinese: '玩具', emoji: '🧸' },
      { key: 'body', name: 'Body', chinese: '身体', emoji: '👋' },
      { key: 'jobs', name: 'Jobs', chinese: '职业', emoji: '👨‍⚕️' },
      { key: 'expressions', name: 'Expressions', chinese: '表情', emoji: '😊' },
      { key: 'vehicles', name: 'Vehicles', chinese: '交通', emoji: '🚗' },
    ];
  },

  /**
   * 获取所有单词
   */
  getAllWords() {
    let all = [];
    this.getCategories().forEach(cat => {
      if (this[cat.key]) {
        all = all.concat(this[cat.key].map(item => ({ ...item, category: cat.key })));
      }
    });
    return all;
  },

  /**
   * 获取单词总数
   */
  getTotalCount() {
    return this.getAllWords().length;
  }
};

// 统计
console.log('WordsData loaded:', WordsData.getTotalCount(), 'words in', WordsData.getCategories().length, 'categories');
